### PR TITLE
chore(bigemojiv2,staffOnDuty): update regex

### PR DESCRIPTION
**Pull request by EsenDR**
**Please describe the changes this PR makes and why it should be merged:**
Simple change, just updating regex for both.

**Status**

- [x] Code changes have been tested on an instance of YAGPDB, or there are no code changes
- [x] I have read and followed the [contribution guide](../CONTRIBUTING.md)

### CODE REVIEW

**Review by l-zeuch — APPROVED** [review]
Esen tryna getting top-contributor

**Comment by dvoraknt** [comment]
what? this breaks both of them as one requires arguments and the other has optional arguments. adding (\s+|\z)(\s+|\z) makes bigemoji completely nonfunctional and breaks half of the on duty system. The yag ping is an understandable alternative addition but whitespace/endline need to be removed

**Comment by l-zeuch** [comment]
It does not. The trigger is directly taken from the `;rgalias` snippet, which we'd know if it does not work as you described.

**Comment by jo3-l** [comment]
> If nothing else, (\s+|\z)(\s+|\z) is incorrect, as it requires at least 2
spaces or EOF.

**Comment by dvoraknt** [comment]
I didn't explain well enough before the edit. Requiring two spaces between trigger and argument is silly

**Comment by l-zeuch** [comment]
This at max - apparently it slipped? dunno. The snippet at least is correct

**Pull request merged**
