### PR TITLE
fix(*): escape server prefixes in regular expressions

### PR DESCRIPTION
**Pull request by galen8183**
**Please describe the changes this PR makes and why it should be merged:**

#270 did not take into account special characters in server prefixes that can cause regex compilation errors, this PR reintroduces `$Escaped_Prefix` (or similar) variables where necessary  

**Status**

- [x] Code changes have been tested on an instance of YAGPDB, or there are no code changes
- [x] I have read and followed the [contribution guide](https://github.com/yagpdb-cc/yagpdb-cc/blob/master/CONTRIBUTING.md)
- [x] I have [written documentation](https://github.com/yagpdb-cc/yagpdb-cc/blob/master/WRITING-DOCUMENTATION.md) for my changes, or there is no need to

### CODE REVIEW

**Comment by jo3-l** [comment]
I'm fairly sure that `reQuoteMeta` can be used to simplify the implementation in some cases here.

**Comment by galen8183** [comment]
Ah, I missed that that had been added, will update momentarily.

**Comment by galen8183** [comment]
I believe that should be done correctly... my proficiency in git is lacking :')

**Review by jo3-l — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
