### PR TITLE
Update afk.go.tmpl

### PR DESCRIPTION
**Pull request by BlackWolfWoof**
**Please describe the changes this PR makes and why it should be merged:**

When using " as prefix it would cause an issue. This patch should fix that. 
It is not really a good patch as it doesn't solve the root problem of it but it still works. Thats why i am not pushing it and just creating a pr for someone else to review.

**Status**

- [x] Code changes have been tested on an instance of YAGPDB, or there are no code changes
- [x] I have read and followed the [contribution guide](../CONTRIBUTING.md)
- [x] I have [written documentation](../WRITING-DOCUMENTATION.md) for my changes, or there is no need to

### CODE REVIEW

**Comment by LemmeCry** [comment]
I don't see any changes...?

**Comment by BlackWolfWoof** [comment]
Hmmm great, ctrl v doesn't work on web...

**Review by l-zeuch — COMMENTED** [review]
As far as I know, this will also break with these prefixes
* ' (Single quotes)
* ` (Backticks)
Seeing as those are also used to denote argument strings.
Unfortunately I'm currently unable to test this hypothesis, but if that is the case, we should consider implementing a similar fallback for those.

**Comment by jo3-l** [comment]
I don't think this is an edge case worth complicating the code for. (Of course, I'm happy to hear arguments to the contrary; did someone using this command come across this problem?)

If we are to fix this issue -- and again, I am unconvinced at the moment that doing so is needed -- I have a different way in mind that is more robust.

**Comment by BlackWolfWoof** [comment]
Yep, someone used it and came to us and said it won't respond.
Also I won't mind if it doesn't get accepted (why did i put 2h into that code aaa) because it is a bit meh the fix xd

**Comment by l-zeuch** [comment]
Closing due to the above.

**Pull request closed without merging**
