### PR TITLE
Yagpdb-Disboard-Reminder

### PR DESCRIPTION
**Pull request by Madhav-byte-debug**
This command helps users to bump their servers more efficiently and help their servers to grow. 
It is just an automatic reminder. It does not violate Disboard's ToS. 
It sends a message asking you if you want to be reminded when you can bump next.
https://github.com/Madhav-byte-debug/Yagpdb-Disboard-Reminder
**Status**

- [ ] Code changes have been tested on an instance of YAGPDB, or there are no code changes
- [ ] I have read and followed the [contribution guide](../CONTRIBUTING.md)

### CODE REVIEW

**Comment by l-zeuch** [comment]
Hi!
Thank you for the pull request.
Unfortunately it looks like a lot of unrelated changes have slipped in, let alone completely missing your added script.

Moreover, as DISBOARDs [guidelines](https://disboard.org/site/guidelines) are *extremely* vague regarding rewards for bumping, I don't think that this is a good addition, because we experienced that their support staff tends to bend the rules to their liking, without actually ever updating their guidelines.
This is simply to keep users of YAGPDB out of possible trouble, nothing personal. If they still want to make such a system, they can feel free to do it themselves.

Lastly, if you want to contribute, you would have to fork the repository, make your changes on your fork and then open a pull request. A quick google search should help you, if you aren't quite familiar with git and GitHub.

Kind regards

**Comment by Madhav-byte-debug** [comment]
Oh no there are no rewards for users. It's simply a reminder thats efficient.
Here are some screenshots. 

Screenshot 2021-05-16 at 12 14 04 PM
Screenshot 2021-05-16 at 12 14 11 PM
Screenshot 2021-05-16 at 12 14 36 PM

**Comment by l-zeuch** [comment]
> we experienced that their support staff tends to bend the rules to their liking, without actually ever updating their guidelines.

Even though you may not reward users, it is better to be safe than sorry. If people want to make their own system, they can feel free to - but as DISBOARD's guidelines are, as I already mentioned, extremely (if not deliberately) vague, I'm -1 on this addition. This is, as I said, just to keep our userbase out of trouble, even though it may not happen. Better safe than sorry.

> Unfortunately it looks like a lot of unrelated changes have slipped in, let alone completely missing your added script.

I don't think you understood this correctly, so allow me to elaborate - I do not see any commits from you that will be added, which invalidates your request. Your script is missing. Even if I merged this pull request (which I won't), your script won't be added, as it is completely missing.

> Lastly, if you want to contribute, you would have to fork the repository, make your changes on your fork and then open a pull request. A quick google search should help you, if you aren't quite familiar with git and GitHub.

**Comment by Madhav-byte-debug** [comment]
Alright. I understand. Thanks for looking into my request.

**Pull request closed without merging**
