### PR TITLE
[feat] add staffOnDuty.go.tmpl

### PR DESCRIPTION
**Pull request by dvoraknt**
**Please describe the changes this PR makes and why it should be merged:**
new CC for an "on duty" staffing system, read header for more information. Tested extensively on both premium and non premium servers. Heavily restricted topic editing to ensure discord ratelimit is not reached

**Status**

- [x] Code changes have been tested on an instance of YAGPDB, or there are no code changes
- [x] I have read and followed the [contribution guide](../CONTRIBUTING.md)

### CODE REVIEW

**Comment by BlackWolfWoof** [comment]
$idiotStaff lmao xd *i am reviewing it rn*

**Comment by dvoraknt** [comment]
> 
> 
> $idiotStaff lmao xd _i am reviewing it rn_

yeah I didn't originally intend for this to go beyond my own server lol. It grew into something that others may also find value in and I thought that was a fine enough variable name

**Comment by BlackWolfWoof** [comment]
I mean I think it's fine 😂
You don't wanna see my variables or comments  on aome cc's that are private hehe

**Review by BlackWolfWoof — APPROVED** [review]
I have tested the custom command and it works fine for me even with multiple users at the same time. I was thinking that the sendDM wouldn't work with multiple staff but it did actually.

Since this is my first time approving such code i will ask @jo3-l to merge it because uhhh yea I didn't do it before.

**Review by DaviiD1337 — APPROVED** [review]

**Comment by l-zeuch** [comment]
Thanks!

**Pull request merged**
