### PR TITLE
Restructure and reformat commands and READMEs

### LINKED ISSUE #40: meta: Change file extensions to .MD?
See title.
## Pros
* Descriptions are easier to read (instead of a leading comment, we can have markdown)
* Eliminates any possible confusion that YAGPDB CC has any relation to Lua or other programming languages
* Can still have syntax highlighting in codeblocks

## Cons
* Harder to copy code on mobile

### LINKED ISSUE #49: request: restructure folders
Im on mobile and am lazy but you should prob move the contents of the util folder into a new "misc" folder with the birthday cmds and such rather than calling it util
Edit: i love not being able to add tags to my own issues :^)

### LINKED ISSUE #53: request: subfolders for individual commands
Rather than changing all the commands to MD files (#40) why not make an individual subfolder for each one with a README file? Seems like its the best of both worlds and it only adds 1 click, its clean and could remove the comments at the top of the files entirely. It would probably make it easier to navigate as well considering there are already some commands that have their own folders.

### LINKED ISSUE #91: bug: empty file for emoji-info cc
While working on #90, I noticed that there was an [empty file for an emoji command](https://github.com/Jo3-L/yagpdb-cc/commits/master/info/emoji/emoji.cc.lua), and no history attached to that file. Did that command get misplaced, or was that command never created?
There was a PR (#9) for that exact file, but it was never merged

### PR DESCRIPTION
**Pull request by thewilloftheshadow**
Mass draft PR for the changes I’m doing as they’re completed for feedback and noting changes :)

Closes #40
Fixes #53
Fixes #49
Fixes #91

### CODE REVIEW

**Comment by thewilloftheshadow** [comment]
Issues #40 (?) and #53 are in this PR

**Comment by thewilloftheshadow** [comment]
Utility folder is complete! I wrote a shell script to automate most of the process, so now I just run for each command and tweak the generated README.md

**Comment by thewilloftheshadow** [comment]
Maintenance is complete!

**Comment by thewilloftheshadow** [comment]
Only have the fun section left and then this is ready for review

**Comment by thewilloftheshadow** [comment]
> having fun?


It was fun for the first 600 commands... now it makes my eyes water 😂😂
I love it though 🤷

**Comment by Jo3-L** [comment]
Will fix up the merge conflicts here myself, don't worry about it @thewilloftheshadow 👍

**Comment by thewilloftheshadow** [comment]
Still missing the [fun folder](https://github.com/yagpdb-cc/yagpdb-cc/tree/master/fun) but I can do that tonight when I'm back on my main machine :+1:

**Comment by Jo3-L** [comment]
Go ahead and finish the fun folder - there's a bunch of merge conflicts and "major" structural changes to the repo which I'd prefer to handle myself. Thank you again for all the work on this, it's very much appreciated!

**Comment by jo3-l** [comment]
Hi, really sad to say that I'm closing this because it's stale. This is not your fault at all; I said I'd review it and clean it up but I never did get a chance to do that. This is partly out of time issues - I don't have as much free time for programming as I did in the summer/quarantine, and partly out of motivation issues - I'm not a huge user of Yag anymore, the only server I admin is my school server which doesn't need many Yag CCs. However, that's not an excuse, I did promise to review this and I'm really sorry that I didn't get a chance to do that considering all the work you've put into this.

However, in the time that has passed since this PR was opened, it's fallen out of date with the main branch. I don't foresee having enough time/motivation to review & clean up this PR until the summer is up, at which point it'll be even more outdated. As such, I feel closing this for the time being (perhaps reopening during the summer) is the best decision I can make currently.

Sorry again for letting all your work here go to waste, it wasn't your fault at all.

**Pull request closed without merging**
