### PR TITLE
Create snipe.go.tmpl

### PR DESCRIPTION
**Pull request by z3nn13**
Snipe Command :D
A Custom Command to fetch the latest deleted message in a channel

- [x] Code changes have been tested on an instance of YAGPDB, or there are no code changes
- [x] I have read and followed the [contribution guide](../CONTRIBUTING.md)

# Preview
image
image2

### CODE REVIEW

**Comment by Wolveric** [comment]
This is literally already a thing in the `-undelete` command...

Yes, YAGPDB doesn't cache files in that case, but multimedia handling is also pretty bandwidth intensive.

**Comment by z3nn13** [comment]
Lol, my bad, i should've included the words custom command, edited it now ^^

**Comment by Wolveric** [comment]
More the case that there's the two repository channels in the server, and I thought I was looking at the source code one... 😂 Idk the particular use of it in this case...

**Review by jo3-l — APPROVED** [review]
Thanks!

**Pull request merged**
