### PR TITLE
fix(reports): hotfix invalid dict call

### LINKED ISSUE #173: bug:An error caused the execution of the custom command template to stop
**Describe the bug in as much detail as possible:**

I get this response when using the caution emoji "to get background info":

> An error caused the execution of the custom command template to stop:

> `Failed executing template: template: CC #10:42:17: executing "edit" at <sdict "name" "Status...>: error calling sdict: invalid dict call
`

**To Reproduce:**

click the caution emoji reaction underneath the embed

**Expected behavior:**
I believe i should see background info if any and something that says there is none if none

**Screenshots:**

CleanShot 2021-03-21 at 21 35 36

**Additional context:**

### PR DESCRIPTION
**Pull request by l-zeuch**
fixes #173
I am an idiot.

**Please describe the changes this PR makes and why it should be merged:**
I am an idiot.
**Status**

- [x] Code changes have been tested on an instance of YAGPDB, or there are no code changes
- [x] I have read and followed the [contribution guide](../CONTRIBUTING.md)

### CODE REVIEW

**Review by azcraze — CHANGES_REQUESTED** [review]
image
should a similar fix occur here?

**Comment by azcraze** [comment]
but that change did fix the other error. I dont know, maybe this is a different issue

**Comment by l-zeuch** [comment]
I just got my long-time exam finished, I'm on the way home.
@jo3-l , don't merge yet, it seems that stepping back a version somehow mixed up a few things.

**Comment by jo3-l** [comment]
@l-zeuch is this ready to merge?

**Comment by l-zeuch** [comment]
Yep! Thanks for waiting on me!

**Pull request merged**
