### PR TITLE
YAGPDB Music Player

### PR DESCRIPTION
**Pull request by Engineer152**
**Please describe the changes this PR makes and why it should be merged:**

These custom commands have been created to turn the YAGPDB soundboard into a fully working music player. Please refer to the website below for setup instructions, and available commands.

Learn how to implement and use this CC here: https://docs.yagpdb-mp.tk/

**Status**

- [X] Code changes have been tested on an instance of YAGPDB, or there are no code changes
- [x] I have read and followed the [contribution guide](../CONTRIBUTING.md)

### CODE REVIEW

**Comment by l-zeuch** [comment]
A few questions:
1. If I got that right, I'd still have to upload the songs as soundfile to the soundboard?
2. Considering that the documentation you linked is a dot-tk, how long is it running for? Will you remember to refresh it?
3. As far as I know, we cannot merge due to clashing licenses, you use AGPL-3.0 and we are licensed under the terms of MIT.

Regarding (3): My own repository is licensed under the terms of AGPL-3.0 as well, this is why I do not have much of my code here, except a few out-of-service versions.

**Comment by l-zeuch** [comment]
Addendum: Blocked until the above questions are addressed and resolved.

**Comment by Engineer152** [comment]
> A few questions:
> 
> 1. If I got that right, I'd still have to upload the songs as soundfile to the soundboard?
> 2. Considering that the documentation you linked is a dot-tk, how long is it running for? Will you remember to refresh it?
> 3. As far as I know, we cannot merge due to clashing licenses, you use AGPL-3.0 and we are licensed under the terms of MIT.
> 
> Regarding (3): My own repository is licensed under the terms of AGPL-3.0 as well, this is why I do not have much of my code here, except a few out-of-service versions.

To answer your questions above:

1. Yes you would have to still upload soundfiles to the soundboard in the following naming format: Artist Name - Song Title [0m0s]

2. Yes, any updates to the code, or any additional commands, we will keep the gitbook updated.

3. I will follow up with license information later on.

**Comment by SpecialEliteSNP** [comment]
I guess we could do the MIT license instead. I just really liked the AGPLv3 one... I understand that making a README would be preferred but that gitbook site is just way better than a simple readme.

**Comment by l-zeuch** [comment]
> Yes you would have to still upload soundfiles to the soundboard in the following naming format:
`Artist Name - Song Title [0m0s]`

Ah, just found it in the documentation - there are still a few images missing, when are those being added? Would kind-of not want to merge when the documentation is yet to be completed.

> Yes, any updates to the code, or any additional commands, we will keep the gitbook updated.

Sounds like you're still working on it - see above. It's a bit more convenient to use an own repository while actively working on a system that still is supported and constantly updated throughout its lifetime, if you get what I mean.

> I will follow up with license information later on.

If you'd still like to keep the license, I'd recommend keeping it in your repository, just like I do, a lot of people have their own.

**Comment by l-zeuch** [comment]
> I guess we could do the MIT license instead. I just really liked the AGPLv3 one... 

If you like it, use it. See my above comment - Not few people have their own repository because they want it under a different license.

> I understand that making a README would be preferred but that gitbook site is just way better than a simple readme.

That is true, especially considering that its documentation is rather massive. In your own repository for example, you could use different files and link between them, or link the page, etc., etc.

I'm kinda heading towards -1 on merging, considering the following:

1. Different license - We don't want to force you giving up privileges you want to have on your code. Should stick with AGPL-3.0 if you chose it initially.
2. Its documentation is pretty massive, and to be frank, some users don't want to click external links, let alone reading the README, as we occasionally experience on the support server.
3. It's still being actively developed, as far as I can tell; So a merge would sort of limit you in your ability to release versions easily, let alone possible beta versions (if you do those).

**Comment by Engineer152** [comment]
I understand the conflicts here with our license, and your concern with us developing the code further. I feel this code is something I have seen requested quite a few times within the YAGPDB discord server, and I think a lot of people would benefit from it. Would you be interested in posting just a Readme file with an included short summary, and examples (with pictures), along with a link to the gitbook in this repo for people to reference? I could also include a disclaimer that this code is not something hosted or updated by your repo. If this is not something you would be interested in, I completely understand. Thanks.

**Comment by jo3-l** [comment]
We are uninterested in pointing people to code that is not hosted on our repo, mainly because of security reasons (nothing personal).

**Comment by buthed010203** [comment]
The other problem with commands for a music player is that jonas has said multiple times that he doesnt want people doing this, the soundboard is **not** meant for music

**Comment by Engineer152** [comment]
Okay, thank you for your time on this, youre welcome to close this PR.

**Comment by l-zeuch** [comment]
Closing at request of the author.

**Pull request closed without merging**
