### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TheHDCrafter**
Replaced old github links from Jo3-L to yagpdb-cc

### CODE REVIEW

**Comment by Olde7325** [comment]
Does not seem as an urgent change, as the old Links still point to the according folders and files in **this** repository, however for consistency it is indeed feasible to update them.

**Comment by TheHDCrafter** [comment]
Also bois if u gimme perms i can review pr's and add stuff here without joe and satty having to do all work alone .-.

**Comment by thewilloftheshadow** [comment]
Those links have been updated already in #90 (if not there, then in the local copy of that branch that needs pushing)

**Comment by TheHDCrafter** [comment]
> Those links have been updated already in #90 (if not there, then in the local copy of that branch that needs pushing)

holy shizzle, you changed a lot of things in ur pr

**Comment by Jo3-L** [comment]
lgtm, thanks!
*also, check your invites, I invited you to the `yagpdb-cc` organization*

**Pull request merged**
